spring:
  application:
    name: rag-poc
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# Configuracao AWS
aws:
  region: us-east-1  # Mantém o Bedrock funcionando
  s3:
    bucket: rag-poc-documentos-936672259676-us-east-2-an
    region: us-east-2  # Região específica para S3
  bedrock:
    model-id: amazon.nova-lite-v1:0
    embedding-model-id: cohere.embed-english-v3


# Vector Store (PostgreSQL + pgvector)
pgvector:
  host: ${PGVECTOR_HOST:localhost}
  port: ${PGVECTOR_PORT:5432}
  database: ${PGVECTOR_DATABASE:rag_db}
  user: ${PGVECTOR_USER:postgres}
  password: ${PGVECTOR_PASSWORD}

# Logging
logging:
  level:
    dev.langchain4j: DEBUG
    com.exemplo: DEBUG